/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_vrndk01_JniClient */

#ifndef _Included_com_example_vrndk01_JniClient
#define _Included_com_example_vrndk01_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_vrndk01_JniClient
 * Method:    AddInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_vrndk01_JniClient_AddInt
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
