/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_arrayndk_JniClient */

#ifndef _Included_com_example_arrayndk_JniClient
#define _Included_com_example_arrayndk_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_arrayndk_JniClient
 * Method:    useArray
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_arrayndk_JniClient_useArray
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
