/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_niming_vrndk03_JniClient */

#ifndef _Included_com_niming_vrndk03_JniClient
#define _Included_com_niming_vrndk03_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_niming_vrndk03_JniClient
 * Method:    useArray
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_niming_vrndk03_JniClient_useArray
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_niming_vrndk03_JniClient
 * Method:    LibMain
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_niming_vrndk03_JniClient_LibMain
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
