/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <gfx.h>
/* Header for class com_android_templateApp_GL2View */

#ifndef _Included_com_android_templateApp_GL2View
#define _Included_com_android_templateApp_GL2View
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_templateApp_GL2View
 * Method:    ToucheBegan
 * Signature: (FFI)V
 */
JNIEXPORT void JNICALL Java_com_android_templateApp_GL2View_ToucheBegan
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     com_android_templateApp_GL2View
 * Method:    ToucheMoved
 * Signature: (FFI)V
 */
JNIEXPORT void JNICALL Java_com_android_templateApp_GL2View_ToucheMoved
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     com_android_templateApp_GL2View
 * Method:    ToucheEnded
 * Signature: (FFI)V
 */
JNIEXPORT void JNICALL Java_com_android_templateApp_GL2View_ToucheEnded
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     com_android_templateApp_GL2View
 * Method:    Init
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_templateApp_GL2View_Init
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_android_templateApp_GL2View
 * Method:    Draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_templateApp_GL2View_Draw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
