/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_templateApp_GL2View_ContextFactory */

#ifndef _Included_com_android_templateApp_GL2View_ContextFactory
#define _Included_com_android_templateApp_GL2View_ContextFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
