/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ztestndk_JniClient */

#ifndef _Included_com_example_ztestndk_JniClient
#define _Included_com_example_ztestndk_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ztestndk_JniClient
 * Method:    getSum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_ztestndk_JniClient_getSum
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_ztestndk_JniClient
 * Method:    getUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ztestndk_JniClient_getUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_example_ztestndk_JniClient
 * Method:    sort
 * Signature: ([II)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_ztestndk_JniClient_sort
  (JNIEnv *, jclass, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
